name: "Mark stale issues and pull requests"

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity.'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity.'
        days-before-stale: 30
        days-before-close: 7
        stale-issue-label: 'stale'
        close-issue-message: 'This issue has been closed due to inactivity.'
        stale-pr-label: 'stale'
        close-pr-message: 'This pull request has been closed due to inactivity.'